style: tech-ja-keitei   # polite Japanese technical style
segmentation:
  headings_as_blocks: true
  list_items_as_blocks: true
translator:
  type: openai
  concurrency: 3
  max_chars_per_call: 1500
  retry:
    max_attempts: 3
    backoff_ms: 500
security:
  redact_logs: true      # do not keep original text in logs
parts:
  charts: false          # enable in v1.1
  smartart: false
  comments: true
  headers_footers: true
  footnotes: true
report:
  diff: true
  summary: true
  format: json
